# Generated by Django 6.0.4 on 2026-05-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
