# Generated by Django 6.0.4 on 2026-05-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0003_recipe_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Stored Base64 encoded image string', null=True),
        ),
    ]
